name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar Angular
        run: npm run build -- --base-href /Abylu_Frontend/

      - name: Desactivar Jekyll
        run: touch dist/abylu-frontend/browser/.nojekyll

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos compilados
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/abylu-frontend/browser

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
